use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, anyhow, bail};
use examples_source::{ExampleArtifact, ad_cost_artifacts, all_examples};
use sx_codegen::{format_rust_source, lower_function};
use sx_codegen_llvm::{
    AotWrapperOptions, LlvmOptimizationLevel, LlvmTarget, emit_object_file_lowered,
    generate_aot_wrapper_module,
};

fn archive_objects(archive_path: &Path, object_paths: &[PathBuf]) -> Result<()> {
    let ar = env::var("AR").unwrap_or_else(|_| "ar".into());
    let output = Command::new(ar)
        .arg("crus")
        .arg(archive_path)
        .args(object_paths)
        .output()?;
    if !output.status.success() {
        bail!(
            "failed to archive LLVM AOT objects: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(())
}

fn cargo_llvm_opt_level() -> LlvmOptimizationLevel {
    env::var("OPT_LEVEL")
        .ok()
        .as_deref()
        .and_then(LlvmOptimizationLevel::from_cargo_opt_level)
        .unwrap_or(LlvmOptimizationLevel::O0)
}

fn cargo_llvm_target() -> Result<LlvmTarget> {
    Ok(LlvmTarget::Triple(env::var("TARGET")?))
}

fn write_llvm_wrapper_bundle(
    rust_path: &Path,
    archive_name: &str,
    artifacts: Vec<ExampleArtifact>,
) -> Result<()> {
    let out_dir = rust_path
        .parent()
        .ok_or_else(|| anyhow!("LLVM wrapper output path must have a parent directory"))?;
    let objects_dir = out_dir.join(format!("{archive_name}_objects"));
    fs::create_dir_all(&objects_dir)?;

    let llvm_opt = cargo_llvm_opt_level();
    let llvm_target = cargo_llvm_target()?;
    let mut source = String::new();
    let mut object_paths = Vec::new();
    source.push_str("// @generated by examples_run/build.rs\n");

    for artifact in artifacts {
        let lowered = lower_function(&artifact.function)?;
        let object_path = objects_dir.join(format!("{}.o", artifact.module_name));
        emit_object_file_lowered(&object_path, &lowered, llvm_opt, &llvm_target)?;
        source.push_str(&generate_aot_wrapper_module(
            &lowered,
            &AotWrapperOptions {
                emit_doc_comments: true,
            },
        )?);
        source.push('\n');
        object_paths.push(object_path);
    }

    fs::write(rust_path, format_rust_source(&source)?)?;

    let archive_path = out_dir.join(format!("lib{archive_name}.a"));
    archive_objects(&archive_path, &object_paths)?;
    println!("cargo:rustc-link-arg={}", archive_path.display());
    Ok(())
}

fn main() -> Result<()> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?).canonicalize()?;
    write_llvm_wrapper_bundle(
        &out_dir.join("generated_examples_llvm_aot.rs"),
        "examples_llvm_aot",
        all_examples().context("failed to build example artifacts")?,
    )?;
    if env::var_os("CARGO_FEATURE_AD_BENCH_ARTIFACTS").is_some() {
        write_llvm_wrapper_bundle(
            &out_dir.join("generated_ad_cost_llvm_aot.rs"),
            "ad_cost_llvm_aot",
            ad_cost_artifacts().context("failed to build AD cost artifacts")?,
        )?;
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../examples_source/src/lib.rs");
    println!("cargo:rerun-if-changed=../sx_core/src");
    println!("cargo:rerun-if-changed=../sx_codegen/src");
    println!("cargo:rerun-if-changed=../sx_codegen_llvm/src");
    Ok(())
}
