[alias]
lint = "clippy --workspace --all-targets"
lint-strict = [
    "clippy",
    "--workspace",
    "--lib",
    "--bins",
    "--examples",
    "--benches",
    "--",
    "-W",
    "clippy::pedantic",
    "-A",
    "clippy::missing_errors_doc",
    "-A",
    "clippy::missing_panics_doc",
    "-A",
    "clippy::must_use_candidate",
    "-A",
    "clippy::return_self_not_must_use",
    "-A",
    "clippy::many_single_char_names",
    "-A",
    "clippy::module_name_repetitions",
    "-A",
    "clippy::cast_possible_truncation",
    "-A",
    "clippy::cast_precision_loss",
    "-A",
    "clippy::cast_sign_loss",
    "-A",
    "clippy::float_cmp",
    "-A",
    "clippy::too_many_lines",
    "-A",
    "clippy::format_push_string",
    "-A",
    "clippy::borrow_as_ptr",
    "-A",
    "clippy::redundant_closure_for_method_calls",
    "-A",
    "clippy::single_char_pattern",
    "-A",
    "clippy::uninlined_format_args",
    "-A",
    "clippy::unnecessary_semicolon",
    "-D",
    "clippy::panic",
    "-D",
    "clippy::unwrap_used",
    "-D",
    "clippy::expect_used",
]
